# Data Science Summer School - Split '17

# 3. Character-wise language modeling with multi-layer LSTMs

This hands-on session is based on two tutorial notebooks [*Intro to Recurrent Networks (Character-wise RNN)*](https://github.com/udacity/deep-learning/tree/master/intro-to-rnns) and [*Tensorboard*](https://github.com/udacity/deep-learning/tree/master/tensorboard) from Udacity's [Deep Learning Nanodegree Foundation](https://www.udacity.com/course/deep-learning-nanodegree-foundation--nd101) program.

This notebook implements a multi-layer LSTMs network for training/sampling from character-level language models. The model takes a text file as input and trains the network that learns to predict the next character in a sequence. The network can then be used to generate text character by character that will look like the original training data. This network is based on Andrej Karpathy's [post on RNNs](http://karpathy.github.io/2015/05/21/rnn-effectiveness/), which became standard example for explaining peculiarities behind RNN models.

In [1]:
import time
from collections import namedtuple

import numpy as np
import tensorflow as tf
tf.logging.set_verbosity(tf.logging.ERROR)

In [2]:
%load_ext autoreload
%autoreload 2
#from utils import show_graph

## 3.1 Data preparation

### Loading and encoding text

We will train our language model on a complete collection of Donald Trump's tweets obtained from [Trump Twitter Archive](http://www.trumptwitterarchive.com/), which we already downloaded and made available in `PATH-TO-REPOSITORY/Day-3/assets/data/trump_tweets_ascii.txt`. First, we will load the text file and encode its characters as integers.

In [3]:
with open('assets/data/trump_tweets_ascii.txt', 'r') as f:
    text=f.read()

# get set of characters contained in the loaded text file
vocab = sorted(set(text))

# encoding characters as integers
vocab_to_int = {c: i for i, c in enumerate(vocab)}
encoded_chars = np.array([vocab_to_int[c] for c in text], dtype=np.int32)

# make dict for decoding intergers to corresponding characters
int_to_vocab = dict(enumerate(vocab))


print('Text size: {}'.format(len(encoded_chars)))
print('Vocabulary size: {}'.format(len(vocab)))
print('*******************************')
print('Number of tweets: {}'.format(len(text.split('\n'))))
print('Median size of a tweet: {}'.format(np.percentile([len(t) for t in text.split('\n')], 50)))

Text size: 2167951
Vocabulary size: 92
*******************************
Number of tweets: 20629
Median size of a tweet: 117.0


In the above output, we can see that `trump_tweets_ascii.txt` contains in total 2 167 951 characters (in comparison, the whole text of Tolstoy's Ana Karenina is 1 798 519 characters, which is 17% less). Tweets contain 92 unique characters which will form a vocabulary for a language model.

Lets see first 300 characters of the provided text:

In [4]:
text[:300]

'We are building our future with American hands American labor American iron aluminum and steel. Happy #LaborDay! https://t.co/lyvtNfQ5IO\nThe United States is considering in addition to other options stopping all trade with any country doing business with North Korea.\nI will be meeting General Kelly '

And see how they are encoded as integers:

In [5]:
encoded_chars[:300]

array([53, 66,  1, 62, 79, 66,  1, 63, 82, 70, 73, 65, 70, 75, 68,  1, 76,
       82, 79,  1, 67, 82, 81, 82, 79, 66,  1, 84, 70, 81, 69,  1, 31, 74,
       66, 79, 70, 64, 62, 75,  1, 69, 62, 75, 65, 80,  1, 31, 74, 66, 79,
       70, 64, 62, 75,  1, 73, 62, 63, 76, 79,  1, 31, 74, 66, 79, 70, 64,
       62, 75,  1, 70, 79, 76, 75,  1, 62, 73, 82, 74, 70, 75, 82, 74,  1,
       62, 75, 65,  1, 80, 81, 66, 66, 73, 14,  1, 38, 62, 77, 77, 86,  1,
        4, 42, 62, 63, 76, 79, 34, 62, 86,  2,  1, 69, 81, 81, 77, 80, 26,
       15, 15, 81, 14, 64, 76, 15, 73, 86, 83, 81, 44, 67, 47, 21, 39, 45,
        0, 50, 69, 66,  1, 51, 75, 70, 81, 66, 65,  1, 49, 81, 62, 81, 66,
       80,  1, 70, 80,  1, 64, 76, 75, 80, 70, 65, 66, 79, 70, 75, 68,  1,
       70, 75,  1, 62, 65, 65, 70, 81, 70, 76, 75,  1, 81, 76,  1, 76, 81,
       69, 66, 79,  1, 76, 77, 81, 70, 76, 75, 80,  1, 80, 81, 76, 77, 77,
       70, 75, 68,  1, 62, 73, 73,  1, 81, 79, 62, 65, 66,  1, 84, 70, 81,
       69,  1, 62, 75, 86

And finally, we check the use of our decoding dict `int_to_vocab` to decode the first 300 encoded characters (which we will be using later while sampling new text from the learned model):

In [6]:
''.join([int_to_vocab[ec] for ec in encoded_chars[:300]])

'We are building our future with American hands American labor American iron aluminum and steel. Happy #LaborDay! https://t.co/lyvtNfQ5IO\nThe United States is considering in addition to other options stopping all trade with any country doing business with North Korea.\nI will be meeting General Kelly '

### Making training and validation mini-batches

Neural networks are trained by approximating the gradient of loss function with respect to the neuron weights, by looking at only a small subset of the data, also known as a mini-batch. Here is where we'll make our mini-batches for training and validation. Now we need to split up the data into batches, and into training and validation sets. 

For the test we will observe how the network generates new text, thus we will not be using test set. We will feed a character into the network and sample a next one from the distribution over characters likely to come next. We feed the sampled character right back to get another next character. Repeating this process character by character will generate new text, hopefully indistinguishable from [Donald Trump's](https://twitter.com/realdonaldtrump/status/881281755017355264) Twitter [tweets](https://twitter.com/realdonaldtrump/status/869858333477523458).


![visualization of batches](assets/images/batches-visualization.png)

In [7]:
def split_data(arr, batch_size, num_steps, split_frac=0.9):
    """ 
    Split data into training and validation sets, inputs and targets for each set.
    
    Arguments
    ---------
    arr: Array of encoded characters as integers 
    batch_size: Number of sequences per batch
    num_steps: Number of sequence steps per batch to keep in the input and pass to the network, max_time
    split_frac: Fraction of batches to keep in the training set
    
    
    Returns train_x, train_y, val_x, val_y
    """
    
    slice_size = batch_size * num_steps
    n_batches = int(len(arr) / slice_size)
    
    # Drop the last few characters to make only full batches
    x = arr[: n_batches*slice_size]
    
    # The targets are the same as the inputs, except shifted one character over.
    # number of batches covers full size of arr (no characters dropped)
    if(len(arr) == n_batches*slice_size):
        # for the last target character use first input character
        y = np.roll(x, -1)
    else:
        # for the last target characher use first dropped character
        y = arr[1: n_batches*slice_size + 1]
    
    # Split the data into batch_size slices, then stack them into a 2D matrix 
    x = np.stack(np.split(x, batch_size))
    y = np.stack(np.split(y, batch_size))
    # faster alternative
    #x = x.reshape((batch_size, -1))
    #y = y.reshape((batch_size, -1))
    
    # Now x and y are arrays with dimensions batch_size x n_batches*num_steps
    
    # Split into training and validation sets, keep the virst split_frac batches for training
    split_idx = int(n_batches*split_frac)
    train_x, train_y= x[:, :split_idx*num_steps], y[:, :split_idx*num_steps]
    val_x, val_y = x[:, split_idx*num_steps:], y[:, split_idx*num_steps:]
    
    return train_x, train_y, val_x, val_y

In [8]:
# example test array
example_arr = np.arange(63)
print(np.array2string(example_arr, max_line_width=100, separator=', '))

[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62]


In [9]:
batch_size = 5 # use 5 sequences in a batch
num_steps = 3 # 'size' of sequence in a batch, max_time
# n_batches = len(arr)/(batch_size*num_steps) = 100/(5*5) = 4

split_frac=0.9 # TRAIN= int(0.9 * n_batches) = 3, VAL= n_batches - TRAIN = 1

In [10]:
train_x, train_y, val_x, val_y = split_data(example_arr, batch_size, num_steps, split_frac)

In [11]:
train_x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [12, 13, 14, 15, 16, 17, 18, 19, 20],
       [24, 25, 26, 27, 28, 29, 30, 31, 32],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [48, 49, 50, 51, 52, 53, 54, 55, 56]])

In [12]:
train_y

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [13, 14, 15, 16, 17, 18, 19, 20, 21],
       [25, 26, 27, 28, 29, 30, 31, 32, 33],
       [37, 38, 39, 40, 41, 42, 43, 44, 45],
       [49, 50, 51, 52, 53, 54, 55, 56, 57]])

Next, we will create a generator function to get batches from the arrays made by `split_data`. This will provide us with the functionality to iterate over batches, which we can feed to our network model. The arrays are of dimension (`batch_size, n_batches*num_steps`). Each batch is a sliding window on these arrays with size `batch_size X num_steps`.

In [13]:
def get_batch(arrs, num_steps):
    batch_size, slice_size = arrs[0].shape
    
    n_batches = int(slice_size/num_steps)
    for b in range(n_batches):
        yield [x[:, b*num_steps: (b+1)*num_steps] for x in arrs]

In [14]:
train_batches = get_batch([train_x, train_y], num_steps)

Now, we will test getting the first batch:

In [15]:
train_batch_x, train_batch_y = next(train_batches)

In [16]:
train_batch_x

array([[ 0,  1,  2],
       [12, 13, 14],
       [24, 25, 26],
       [36, 37, 38],
       [48, 49, 50]])

In [17]:
train_batch_y

array([[ 1,  2,  3],
       [13, 14, 15],
       [25, 26, 27],
       [37, 38, 39],
       [49, 50, 51]])

In [18]:
train_batch_x, train_batch_y = next(train_batches)

Next, we can get the second one:

In [19]:
train_batch_x

array([[ 3,  4,  5],
       [15, 16, 17],
       [27, 28, 29],
       [39, 40, 41],
       [51, 52, 53]])

In [20]:
train_batch_y

array([[ 4,  5,  6],
       [16, 17, 18],
       [28, 29, 30],
       [40, 41, 42],
       [52, 53, 54]])

In [21]:
'(batch_size, num_steps) = {}'.format(train_batch_x.shape)

'(batch_size, num_steps) = (5, 3)'

However, we will be iterating over batches using the 'for loop':

In [22]:
print("TRAIN BATCHES")
for b, (x, y) in enumerate(get_batch([train_x, train_y], num_steps), 1):
    print('\nBatch {}:'.format(b))
    print(np.stack([x,y]))

TRAIN BATCHES

Batch 1:
[[[ 0  1  2]
  [12 13 14]
  [24 25 26]
  [36 37 38]
  [48 49 50]]

 [[ 1  2  3]
  [13 14 15]
  [25 26 27]
  [37 38 39]
  [49 50 51]]]

Batch 2:
[[[ 3  4  5]
  [15 16 17]
  [27 28 29]
  [39 40 41]
  [51 52 53]]

 [[ 4  5  6]
  [16 17 18]
  [28 29 30]
  [40 41 42]
  [52 53 54]]]

Batch 3:
[[[ 6  7  8]
  [18 19 20]
  [30 31 32]
  [42 43 44]
  [54 55 56]]

 [[ 7  8  9]
  [19 20 21]
  [31 32 33]
  [43 44 45]
  [55 56 57]]]


In [23]:
print("VALIDATION BATCHES")
for b, (x, y) in enumerate(get_batch([val_x, val_y], num_steps), 1):
    print('\nBatch {}:'.format(b))
    print(np.stack([x,y]))

VAL BATCHES

Batch 1:
[[[ 9 10 11]
  [21 22 23]
  [33 34 35]
  [45 46 47]
  [57 58 59]]

 [[10 11 12]
  [22 23 24]
  [34 35 36]
  [46 47 48]
  [58 59 60]]]


## 3.2 Building the model

After having our data prepared and convenience functions `split_data` and `get_batch` for handling the data during the training of our model, we can finally start building the model using the TensorFlow library. We will break the model building into five parts:
* building input placeholders for x, y and dropout 
* building multi-layer RNN with stacked LSTM cells
* building softmax output layer
* computation for training loss
* building the optimizer for the model parameters





### Inputs
First, we will create our input placeholders for Tensorflow computational graph of the model. As we are building supervised learning model, we need to declare placeholders for inputs (x) and targets (y). We also need to one-hot encode the input and target tokens, remember we're getting them as encoded characters. Here, we will also declare scalar placeholder for output keep probablity of LSTM cells called `keep_prob`.  

In [24]:
def build_inputs(batch_size, num_steps, num_classes):
    ''' Define placeholders for inputs, targets, and dropout 
    
        Arguments
        ---------
        batch_size: Batch size, number of sequences per batch
        num_steps: Number of sequence steps in a batch
        
    '''
    # Declare placeholders we'll feed into the graph
    
    #Declare placeholder for inputs (x) and one hot encode inputs
    with tf.name_scope('inputs'):
        inputs = tf.placeholder(tf.int32, [batch_size, num_steps], name='inputs')
        x_one_hot = tf.one_hot(inputs, num_classes, name='x_one_hot')
    
    #Declare placeholder for targets (y) and one hot encode targets
    with tf.name_scope('targets'):
        targets = tf.placeholder(tf.int32, [batch_size, num_steps], name='targets')
        y_one_hot = tf.one_hot(targets, num_classes, name='y_one_hot')
    
    # Keep probability placeholder for drop out layers
    keep_prob = tf.placeholder(tf.float32, name='keep_prob')
    
    return inputs, x_one_hot, targets, y_one_hot, keep_prob

### Multi-layer LSTM Cell
We first implement `build_cell` function where we create the LSTM cell we will use in the hidden layer. We will use this cell as a building block for the multi layer RNN. Afterwards, we implement the `build_lstm` function to create multiple LSTM cells stacked on each other using build_cell function. We can stack up the LSTM cells into layers with tf.contrib.rnn.MultiRNNCell. Finally, we create an initial state of all zeros for the MultiRNNCell.

In [25]:
def build_cell(lstm_size, keep_prob):
    # Use a basic LSTM cell
    lstm = tf.contrib.rnn.BasicLSTMCell(lstm_size)

    # Add dropout to the cell
    drop = tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
    return drop

In [26]:
def build_lstm(lstm_size, num_layers, batch_size, keep_prob):
    ''' Build LSTM cell.
    
        Arguments
        ---------
        keep_prob: Scalar tensor (tf.placeholder) for the dropout keep probability
        lstm_size: Size of the hidden layers in the LSTM cells
        num_layers: Number of LSTM layers
        batch_size: Batch size

    '''
    
    # Stack up multiple LSTM layers, for deep learning
    cell = tf.contrib.rnn.MultiRNNCell([build_cell(lstm_size, keep_prob) for _ in range(num_layers)])
    
    with tf.name_scope("RNN_init_state"):
        initial_state = cell.zero_state(batch_size, tf.float32)
    
    return cell, initial_state

### RNN Output
Here we'll create the output layer. We need to connect the output of the RNN cells to a full connected layer with a softmax output. The softmax output gives us a probability distribution we can use to predict the next character. The output 3D tensor with size $(batch\_size \times num\_steps \times lstm\_size)$ has to be reshaped to $((batch\_size * num\_steps) \times  lstm\_size)$, so we can do the matrix multiplication with the softmax weights.


In [28]:
def build_output(lstm_output, in_size, out_size):
    ''' Build a softmax layer, return the softmax output and logits.
    
        Arguments
        ---------
        
        x: Input tensor
        in_size: Size of the input tensor, for example, size of the LSTM cells
        out_size: Size of this softmax layer
    
    '''

    # Reshape output so it's a bunch of rows, one row for each step for each sequence.
    # That is, the shape should be batch_size*num_steps rows by lstm_size columns
    with tf.name_scope('sequence_reshape'):
        seq_output = tf.concat(lstm_output, axis=1, name='seq_output')
        x = tf.reshape(seq_output, [-1, in_size], name='graph_output')
    
    # Connect the RNN outputs to a softmax layer
    with tf.name_scope('logits'):
        softmax_w = tf.Variable(tf.truncated_normal((in_size, out_size), stddev=0.1), name='softmax_w')
        softmax_b = tf.Variable(tf.zeros(out_size), name='softmax_b')
        
        # Since output is a bunch of rows of RNN cell outputs, logits will be a bunch
        # of rows of logit outputs, one for each step and sequence
        logits = tf.matmul(x, softmax_w) + softmax_b
        
        # Tensorboard
        tf.summary.histogram('h_softmax_w', softmax_w)
        tf.summary.histogram('h_softmax_b', softmax_b)
    

    # Use softmax to get the probabilities for predicted characters
    with tf.name_scope('predictions'):
        out = tf.nn.softmax(logits, name='predictions')
        
        # Tensorboard
        tf.summary.histogram('h_predictions', out)
    
    
    return out, logits

### Training loss

Next up is the training loss. We get the logits and targets and calculate the softmax cross-entropy loss. First, reshape the one-hot targets so it's a 2D tensor with size $((batch\_size * num\_steps) \times  num\_classes)$, which match logits. Remember that we reshaped the LSTM outputs and ran them through a fully connected layer with num\_classes units. Then we run the logits and targets through `tf.nn.softmax_cross_entropy_with_logits` and find the mean to get the loss.

In [29]:
def build_loss(logits, y_one_hot, lstm_size):
    ''' Calculate the loss from the logits and the targets.
    
        Arguments
        ---------
        logits: Logits from final fully connected layer
        t
        lstm_size: Number of LSTM hidden units
        num_classes: Number of classes in targets
        
    '''
    
    # Softmax cross entropy loss
    with tf.name_scope('loss'):
        # reshape one-hot encoded targets to match logits, one row per batch_size per step
        y_reshaped = tf.reshape(y_one_hot, logits.get_shape(), name='y_reshaped')
        
        loss = tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=y_reshaped, name='loss')
        cost = tf.reduce_mean(loss, name='cost')
        
        # Tensorboard
        tf.summary.scalar('s_cost', cost)
    
    return cost

### Optimizer

Here we build the optimizer. Normal RNNs have have issues gradients exploding and disappearing. LSTMs fix the disappearance problem, but the gradients can still grow without bound. To fix this, we can clip the gradients above some threshold. That is, if a gradient is larger than that threshold, we set it to the threshold. This will ensure the gradients never grow overly large. Then we use an AdamOptimizer for the learning step.

In [30]:
def build_optimizer(loss, learning_rate, grad_clip):
    ''' Build optmizer for training, using gradient clipping.
    
        Arguments:
        loss: Network loss
        learning_rate: Learning rate for optimizer
    
    '''
    
    # Optimizer for training, using gradient clipping to control exploding gradients
    with tf.name_scope('optimizer'):
        tvars = tf.trainable_variables()
        grads, _ = tf.clip_by_global_norm(tf.gradients(loss, tvars), grad_clip)
        train_op = tf.train.AdamOptimizer(learning_rate)
        optimizer = train_op.apply_gradients(zip(grads, tvars))
    
    return optimizer

### Build the network

Now we can put all the pieces together and build a class for the network. To actually run data through the LSTM cells, we will use [`tf.nn.dynamic_rnn`](https://www.tensorflow.org/versions/r1.0/api_docs/python/tf/nn/dynamic_rnn). This function will pass the hidden and cell states across LSTM cells appropriately for us. It returns the outputs for each LSTM cell at each step for each sequence in the mini-batch. It also gives us the final LSTM state. We want to save this state as `final_state` so we can pass it to the first LSTM cell in the the next mini-batch run. For `tf.nn.dynamic_rnn`, we pass in the cell and initial state we get from `build_lstm`, as well as our input sequences.

In [31]:
class CharRNN:
    
    def __init__(self, num_classes, batch_size=64, num_steps=50, 
                       lstm_size=128, num_layers=2, learning_rate=0.001, 
                       grad_clip=5, sampling=False):
    
        # When we're using this network for sampling later, we'll be passing in
        # one character at a time, so providing an option for that
        if sampling == True:
            batch_size, num_steps = 1, 1
        else:
            batch_size, num_steps = batch_size, num_steps

        tf.reset_default_graph()
        
        # Build the input placeholder tensors, and one-hot encode the input and target tokens
        self.inputs, x_one_hot, self.targets, y_one_hot, self.keep_prob = \
        build_inputs(batch_size, num_steps, num_classes)
        
        # Build the LSTM cell
        cell, self.initial_state = build_lstm(lstm_size, num_layers, batch_size, self.keep_prob)
 
        # Run each sequence step through the RNN and collect the outputs
        with tf.name_scope("RNN_forward"):
            outputs, state = tf.nn.dynamic_rnn(cell, x_one_hot, initial_state=self.initial_state)
        
        self.final_state = state
        
        # Get softmax predictions and logits
        self.prediction, self.logits = build_output(outputs, lstm_size, num_classes)
        
        # Loss and optimizer (with gradient clipping)
        self.loss = build_loss(self.logits, y_one_hot, lstm_size)
        self.optimizer = build_optimizer(self.loss, learning_rate, grad_clip)
        
        self.summary_merged = tf.summary.merge_all()

### Hyperparameters

Here we declare the hyperparameters for the network. 

* `batch_size` - Number of sequences running through the network in one pass.
* `num_steps` - Number of characters in the sequence the network is trained on. Larger is better typically, the network will learn more long range dependencies. But it takes longer to train. 100 is typically a good number here.
* `lstm_size` - The number of units in the hidden layers.
* `num_layers` - Number of hidden LSTM layers to use
* `learning_rate` - Learning rate for training
* `keep_prob` - The dropout keep probability when training. If you're network is overfitting, try decreasing this.

Here's some good advice from Andrej Karpathy on training the network [https://github.com/karpathy/char-rnn#tips-and-tricks](https://github.com/karpathy/char-rnn#tips-and-tricks).



In [32]:
batch_size = 100        # Sequences per batch
num_steps = 100         # Number of sequence steps per batch
lstm_size = 512         # Size of hidden layers in LSTMs
num_layers = 2          # Number of LSTM layers
learning_rate = 0.001   # Learning rate
keep_prob = 0.5         # Dropout keep probability

### Number of parameters

LSTM cell: $4 \times \big[N_{units} \times (N_{inputs}+1) + N_{units}^{2}\big]; N_{units}=lstm\_size, N_{inputs}=len(vocab)$

In [33]:
print("lstm_size = {}".format(lstm_size))
print("input size = {}".format(len(vocab)))

lstm_size = 512
input size = 92


In [34]:
model = CharRNN(len(vocab), batch_size=batch_size, num_steps=num_steps,
                lstm_size=lstm_size, num_layers=num_layers, 
                learning_rate=learning_rate)

In [35]:
tf.trainable_variables()

[<tf.Variable 'rnn/multi_rnn_cell/cell_0/basic_lstm_cell/kernel:0' shape=(604, 2048) dtype=float32_ref>,
 <tf.Variable 'rnn/multi_rnn_cell/cell_0/basic_lstm_cell/bias:0' shape=(2048,) dtype=float32_ref>,
 <tf.Variable 'rnn/multi_rnn_cell/cell_1/basic_lstm_cell/kernel:0' shape=(1024, 2048) dtype=float32_ref>,
 <tf.Variable 'rnn/multi_rnn_cell/cell_1/basic_lstm_cell/bias:0' shape=(2048,) dtype=float32_ref>,
 <tf.Variable 'logits/softmax_w:0' shape=(512, 92) dtype=float32_ref>,
 <tf.Variable 'logits/softmax_b:0' shape=(92,) dtype=float32_ref>]

### Write out the graph for TensorBoard

In [36]:
model = CharRNN(len(vocab), batch_size=batch_size, num_steps=num_steps,
                lstm_size=lstm_size, num_layers=num_layers, 
                learning_rate=learning_rate)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    file_writer = tf.summary.FileWriter('assets/logs/1', sess.graph)
    
    file_writer.close()

#run tensorboard from command line by issuing command (e.g. from root repository directory):
#tensorboard --logdir=Day-3/assets/logs/

### Run nodes in the graph

In [37]:
train_x, train_y, val_x, val_y = split_data(encoded_chars, batch_size, num_steps)

model = CharRNN(len(vocab), batch_size=batch_size, num_steps=num_steps,
                lstm_size=lstm_size, num_layers=num_layers, 
                learning_rate=learning_rate)


with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    file_writer = tf.summary.FileWriter('assets/logs/2', sess.graph)
    
    new_state = sess.run(model.initial_state)
    x, y = next(get_batch([train_x, train_y], num_steps))
    
    feed = {model.inputs: x,
        model.targets: y,
        model.keep_prob: 0.5,
        model.initial_state: new_state}
    
    summary, batch_loss, new_state = sess.run([model.summary_merged, model.loss, model.final_state], feed_dict=feed)
    
    file_writer.add_summary(summary, 0)
    
    file_writer.close()

In [38]:
batch_loss

4.5221243

In [39]:
'Number of layers : {}'.format(len(new_state))

'Number of layers : 2'

In [40]:
type(new_state[0]), type(new_state[1])

(tensorflow.python.ops.rnn_cell_impl.LSTMStateTuple,
 tensorflow.python.ops.rnn_cell_impl.LSTMStateTuple)

In [41]:
new_state[1].c.shape, new_state[1].h.shape

((100, 512), (100, 512))

## 3.3 Training model

This is typical training code, passing inputs and targets into the network, then running the optimizer. Here we also get back the final LSTM state for the mini-batch. Then, we pass that state back into the network so the next batch can continue the state from the previous batch. And every so often (set by `save_every_n`) we calculate the validation loss and save a checkpoint.

In [42]:
epochs = 1 #20
save_every_n = 200
train_x, train_y, val_x, val_y = split_data(encoded_chars, batch_size, num_steps)


model = CharRNN(len(vocab), batch_size=batch_size, num_steps=num_steps,
                lstm_size=lstm_size, num_layers=num_layers, 
                learning_rate=learning_rate)

saver = tf.train.Saver(max_to_keep=100)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    train_writer = tf.summary.FileWriter('assets/logs/3/train', sess.graph)
    test_writer = tf.summary.FileWriter('assets/logs/3/test')
    
    #############################################################
    # Use the line below to load a checkpoint and resume training
    # Plase download provided checkpoint files from the link
    # https://www.dropbox.com/s/2eaunmgmvc10n6q/trump_tb_20_i3880_l512_1.327.ckpt.zip?dl=0
    # and place them in assets/checkpoints/ssds direcory in the repositoy
    saver.restore(sess, 'assets/checkpoints/ssds/trump_tb_20_i3880_l512_1.327.ckpt')
    #############################################################
    
    n_batches = int(train_x.shape[1]/num_steps)
    iterations = n_batches * epochs
    for e in range(epochs):
        
        # Train network
        new_state = sess.run(model.initial_state)
        loss = 0
        for b, (x, y) in enumerate(get_batch([train_x, train_y], num_steps), 1):
            iteration = e*n_batches + b
            start = time.time()
            feed = {model.inputs: x,
                    model.targets: y,
                    model.keep_prob: 0.5,
                    model.initial_state: new_state}
            summary, batch_loss, new_state, _ = sess.run([model.summary_merged, model.loss, model.final_state, model.optimizer], 
                                                 feed_dict=feed)
            loss += batch_loss
            end = time.time()
            print('Epoch {}/{} '.format(e+1, epochs),
                  'Iteration {}/{}'.format(iteration, iterations),
                  'Training loss: {:.4f}'.format(loss/b),
                  '{:.4f} sec/batch'.format((end-start)))
            
            train_writer.add_summary(summary, iteration)
        
            if (iteration%save_every_n == 0) or (iteration == iterations):
                # Check performance, notice dropout has been set to 1
                val_loss = []
                new_state = sess.run(model.initial_state)
                for x, y in get_batch([val_x, val_y], num_steps):
                    feed = {model.inputs: x,
                            model.targets: y,
                            model.keep_prob: 1.,
                            model.initial_state: new_state}
                    summary, batch_loss, new_state = sess.run([model.summary_merged, model.loss, model.final_state], feed_dict=feed)
                    val_loss.append(batch_loss)
                
                test_writer.add_summary(summary, iteration)

                print('Validation loss:', np.mean(val_loss),
                      'Saving checkpoint!')
                saver.save(sess, "assets/checkpoints/trump/trump_new_i{}_l{}_{:.3f}.ckpt".format(iteration, lstm_size, np.mean(val_loss)))

Epoch 1/1  Iteration 1/194 Training loss: 1.4728 3.7956 sec/batch
Epoch 1/1  Iteration 2/194 Training loss: 1.4089 3.3319 sec/batch
Epoch 1/1  Iteration 3/194 Training loss: 1.4148 3.1391 sec/batch
Epoch 1/1  Iteration 4/194 Training loss: 1.4073 3.2283 sec/batch
Epoch 1/1  Iteration 5/194 Training loss: 1.3930 3.3912 sec/batch
Epoch 1/1  Iteration 6/194 Training loss: 1.3918 3.5311 sec/batch
Epoch 1/1  Iteration 7/194 Training loss: 1.3907 3.6825 sec/batch
Epoch 1/1  Iteration 8/194 Training loss: 1.3917 3.8574 sec/batch
Epoch 1/1  Iteration 9/194 Training loss: 1.3918 3.8905 sec/batch
Epoch 1/1  Iteration 10/194 Training loss: 1.3906 3.9573 sec/batch
Epoch 1/1  Iteration 11/194 Training loss: 1.3850 3.9808 sec/batch
Epoch 1/1  Iteration 12/194 Training loss: 1.3832 4.0634 sec/batch
Epoch 1/1  Iteration 13/194 Training loss: 1.3862 4.0732 sec/batch
Epoch 1/1  Iteration 14/194 Training loss: 1.3859 4.0716 sec/batch
Epoch 1/1  Iteration 15/194 Training loss: 1.3843 4.3468 sec/batch
Epoc

Epoch 1/1  Iteration 124/194 Training loss: 1.3741 4.4912 sec/batch
Epoch 1/1  Iteration 125/194 Training loss: 1.3742 4.5684 sec/batch
Epoch 1/1  Iteration 126/194 Training loss: 1.3743 4.4625 sec/batch
Epoch 1/1  Iteration 127/194 Training loss: 1.3741 4.4856 sec/batch
Epoch 1/1  Iteration 128/194 Training loss: 1.3741 4.5013 sec/batch
Epoch 1/1  Iteration 129/194 Training loss: 1.3743 4.4631 sec/batch
Epoch 1/1  Iteration 130/194 Training loss: 1.3744 4.3345 sec/batch
Epoch 1/1  Iteration 131/194 Training loss: 1.3745 4.3604 sec/batch
Epoch 1/1  Iteration 132/194 Training loss: 1.3748 4.5095 sec/batch
Epoch 1/1  Iteration 133/194 Training loss: 1.3751 4.4772 sec/batch
Epoch 1/1  Iteration 134/194 Training loss: 1.3753 4.5417 sec/batch
Epoch 1/1  Iteration 135/194 Training loss: 1.3754 4.5123 sec/batch
Epoch 1/1  Iteration 136/194 Training loss: 1.3752 4.3161 sec/batch
Epoch 1/1  Iteration 137/194 Training loss: 1.3749 4.3564 sec/batch
Epoch 1/1  Iteration 138/194 Training loss: 1.37

### Saved checkpoints

Read up on saving and loading checkpoints here: https://www.tensorflow.org/programmers_guide/variables

In [43]:
tf.train.get_checkpoint_state('assets/checkpoints/trump')

model_checkpoint_path: "assets/checkpoints/trump/trump_new_i194_l512_1.321.ckpt"
all_model_checkpoint_paths: "assets/checkpoints/trump/trump_new_i194_l512_1.321.ckpt"

## 3.4 Testing model - sampling from the model

In [44]:
from IPython.core.display import display, HTML

In [45]:
def pick_top_n(preds, vocab_size, top_n=5):
    p = np.squeeze(preds)
    p[np.argsort(p)[:-top_n]] = 0
    p = p / np.sum(p)
    c = np.random.choice(vocab_size, 1, p=p)[0]
    return c

In [46]:
def sample_model(checkpoint, n_samples, lstm_size, vocab_size, num_layers=2, prime="The "):
    samples = [c for c in prime]
    model = CharRNN(len(vocab), lstm_size=lstm_size, num_layers=num_layers, sampling=True)
    saver = tf.train.Saver()
    
    states = []
    with tf.Session() as sess:
        saver.restore(sess, checkpoint)
        new_state = sess.run(model.initial_state)
         
        for c in prime:
            x = np.zeros((1, 1))
            x[0,0] = vocab_to_int[c]
            feed = {model.inputs: x,
                    model.keep_prob: 1.,
                    model.initial_state: new_state}
            preds, new_state = sess.run([model.prediction, model.final_state], 
                                         feed_dict=feed)
      
            states.append(new_state)
    
        c = pick_top_n(preds, len(vocab))
        samples.append(int_to_vocab[c])
        states.append(new_state)

        for i in range(n_samples):
            x[0,0] = c
            feed = {model.inputs: x,
                    model.keep_prob: 1.,
                    model.initial_state: new_state}
            preds, new_state = sess.run([model.prediction, model.final_state], 
                                         feed_dict=feed)

            c = pick_top_n(preds, len(vocab))
            samples.append(int_to_vocab[c])
            states.append(new_state)
        
    return (''.join(samples), states)

In [47]:
checkpoint = tf.train.latest_checkpoint('assets/checkpoints/trump')
samp, _ = sample_model(checkpoint, 160, lstm_size, len(vocab), prime="Obama")
print(samp)


Obama's difficults at a boaldroom and a total success.
We are all truly appreciated to stead the problem into the world has stated that the military don't know who do


Plase download provided checkpoint files from the Dropbox shared link
[https://www.dropbox.com/s/2eaunmgmvc10n6q/trump_tb_20_i3880_l512_1.327.ckpt.zip?dl=0](https://www.dropbox.com/s/2eaunmgmvc10n6q/trump_tb_20_i3880_l512_1.327.ckpt.zip?dl=0)
 and place them in `assets/checkpoints/ssds` direcory in the repositoy.

In [48]:
checkpoint = 'assets/checkpoints/ssds/trump_tb_20_i3880_l512_1.327.ckpt'
samp, _ = sample_model(checkpoint, 1000, lstm_size, len(vocab), prime="Obama (")
print(samp)

Obama (as I will) at 9 PM on @NBCNews!
We should how back the plane against @Alstaneadrist there was going to see this move influst interview with the president of a lead and so budy with him!
The @BarackObama should ask the U.S. and the USS they don't know that they will be such bigger support. The more is taking the word in the world!
"If you have to be doing a businesses that the website is the powerful carable" that they watch the sad to be sure this?
The plane attacked all opportunities in the presidential complitations of me. I'm like them. I lose the best of the baster of another supporting at their day.
.@MittRomney is taking able to stop their country. He could serious that he is to see the meeting on his border.
This is a special support--who should never go and as a big most beautiful time in the world. He can't believe also the big part for the people. We are no lose stupid. So bad ore to see!
The @WWE http://t.co/ss5BiBcsve
This missuch and the presidency and he is a terri

In [49]:
checkpoint = 'assets/checkpoints/ssds/trump_tb_20_i3880_l512_1.327.ckpt'
samp, _ = sample_model(checkpoint, 1000, lstm_size, len(vocab), num_layers=1, prime="Obama (")
print(samp)

Obama (ifA@M1s6|*0eM\\*enn~neMWPCDgshzA+0MMc1rzgscVScMM}cRrV0M~\[M6~mM\}0GMV*RrU0g0tmb|0mhMug0c6M|1cDsMg0d\XMc0VcRrE;[~}mVVM~cGPMSVNMV\z\~Rm:0a;[~//Z}}y/i~iPPinMnz6mg1hliomhk0cwVphzr0MM0M}c0gg1hd~mreq7ed=Mm z}MXocDsghgthah0c1GdSb\citmd1c1Md1scVPSMZ1MVV}0oM}cMWXSMVcE/e}}/\*a}|`})KPSSms//m6} /;]}_/][}_/~[/Z/[/Z:_=}/m]|[[o K}tnhUo=oNca3/o=oNtnPs6$~o~[=$~_=[}}o[[[ m k)V~CZNcE1hl$oofPsa+=am6PmnPso~Nmr a{~ mXo\~ssm/Xnnrrao[oa[mm o[o|||rr nP8no|||nnrvvV(o|@so@resyj girstimhk o
KnkE+&_cB%P6G1P~111|[|=irisWS6mnrnnrvoVVcoCCwm 1$_}`o=io$Se`=am\Pna[[}{})%S K`~BNcjN 1|$s3|`==3 []{~~~ ~~ [~PnNoN w:44@Rsc6siria$a@RmesIZ1tto$Ss_/}/}}naa$][[/[[Z}/~Z}SnetPsj_e`+}tttTT@/X]][_}/}m6Sn[_|[m b[M__%\:hk\|\]erraiCnaa7~n[%s m a[}o  a`\}a||oooNoa|$sm a$Moe[P|a\~onaa[`aa}.]mVPooa$a@mm6mo{}atc6soP_oaionnwrnnNrYTHnnEnIRscHEm
n~6Md}oMfhInnncM6Cm51d}FV|rtroe{}||\=Rgsr~$][=} _}{~ a[}{})}TcE/s9~i~[}}ntcSSNNnof[Psj_e}~cZPCjSt5a`2~$Cs6C/s6|=oN ~[[~Z Z=$Cm 1m=S lZZVPeNotjToNnna[~na%Unia|[sn/roV\naoNRsy/h6noo[ ~[~/ a|]nrnn

In [50]:
checkpoint = 'assets/checkpoints/ssds/trump_tb_20_i3880_l512_1.327.ckpt'
samp, _ = sample_model(checkpoint, 1000, lstm_size, len(vocab), num_layers=2, prime="Obama (")
print(samp)

Obama (can our more) is a great job in the place.
Threat your borders and to step the many the finances and that happening is spending it. Say!
Today I am great for your sending my failure is going to take the billicare and that it's not be and supported the makes. Will never be able!
This is a bad. I am good for the person in the Washington D.C. today. #CarcularyFriends https://t.co/ssIhI200az
Mareland Chris Walda a true honor to make a like his some decision they will have always going to think absolute...
If @BeradeJlands is a failure in Cridea. I will gove to my that we were the press conversation while will discuss one to be the full course!
@menteresolios Trade and thanks.
@mikeymomon Thanks.
@MittRomney I have always been an election in all of themees of millions of the court. Should be their sending!
The @WWE Hall with @ApprenticeNBC is to see a great polls with the with political college. We're niver to get the families?  http://t.co/s255ssi0 They have big security the problem

## 3.5 Visualization of memory cell activations

In [51]:
from IPython.core.display import display, HTML
from utils import save_lstm_vis, make_colored_text

In [52]:
checkpoint = 'assets/checkpoints/ssds/trump_tb_20_i3880_l512_1.327.ckpt'
samp, states = sample_model(checkpoint, 1000, lstm_size, len(vocab), prime="Obama (")
print(samp)

Obama (cont) http://t.co/sB5YB08J
Thank you Melania. The beautiful college and attacks at the White House and this. They are saying a good crudio show.
I like a senties to stead as the policy spending a security or a said a big money-to brong about thit to be so surprosed incledent on the second of military.
@BillGrolfire http://t.co/22Bshisshv
The United Statess stould to be a big ple said as a terrific primary and terrorists and top the standard tomorrow. Would be the grobpon. I will be in Celebrity Apprentice.
Who will have also great at the @CharliesMors tonight at 12:30. Except and so much to get tough because it won't be the place and tough at the U.S. to succeed will be the people of the U.S. will be getting toral from missales!
Will be on @foxandfriends on Macy's incredible time to ster out of today's #TheTerbets and so badly when they had talking about her.
The USA and tax as a fortime out the polls is the military of his chosens will do with making a great guy is not our good

In [53]:
HTML(make_colored_text(samp, states, cell_id=200, layer_id=1))

In [54]:
HTML(make_colored_text(samp, states, cell_id=200, layer_id=0))

In [55]:
save_lstm_vis("CA_trump_tb_20_i3880_l512_1.327", samp, states)

Number of layers: 2
Number of memory cells (LSTM size): 512
Saving CA_trump_tb_20_i3880_l512_1.327_0.html...
Saving CA_trump_tb_20_i3880_l512_1.327_1.html...


## Guessing game

In this section you will play a short game of guessing whether the tweet you are shown is real or generated.

In [ ]:
with open('assets/data/trump tweets ascii.txt') as f:
    tweets_real = f.readlines()

with open('assets/data/trump tweets fake.txt') as f:
    tweets_fake = f.readlines()

In [ ]:
score = 0
N = 10
for i in range(N):
    tweet_label = True
    if random.random() <= 0.5:
        tweet_text = random.choice(tweets_real)
    else:
        tweet_text = random.choice(tweets_fake)
        tweet_label = False
    print("\nTweet " + str(i+1) + "/" + str(N) + ": " + tweet_text)
    answer = bool(int(raw_input("true (1) or fake (0): ")))
    if answer^tweet_label:
        print("WRONG!")
    else:
        print("RIGHT!")
        score = score + 1

print '\nYour score: ' + str(score) + '/' + str(N)